### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tamasban** [laurencelundblade/t_cose#10]
Hi,

This link is not valid anymore (mentioned in README.md):
https://git.trustedfirmware.org/trusted-firmware-m.git/tree/docs/coding_guide.rst

New location of ARM's coding guidleine:
https://git.trustedfirmware.org/trusted-firmware-m.git/tree/docs/about/coding_guide.rst

**Comment by laurencelundblade** [comment]
fixed with b6d5e131ecfa4b3096bf7b80ffe029643774ef50
