### ISSUE TITLE
Use the validate/compute hmac naming in the crypto adaptor layer.

### ISSUE THREAD

**Issue by laurencelundblade** [laurencelundblade/t_cose#103]
Some of the function names are aligned with the PSA API naming, not with the t_cose naming for Mac0 functions.

**Comment by davidvincze** [comment]
@laurencelundblade could you provide more information about this? 
Do you want "sign/verify" replaced in t_cose_crypto.h with "compute/validate" ?

**Comment by laurencelundblade** [comment]
Yes, looks like you got it. Thx. Hopefully I can merge soon (but there's a big merge from master->dev on the way that will need resolving).

**Comment by davidvincze** [comment]
> that will need resolving).

Thank you. Please ping me if the PRs need to be rebased manually, but I'll try to keep them updated.

**Comment by laurencelundblade** [comment]
Fixed by #119
