### ISSUE TITLE
Interface change request for Detached Content

### ISSUE THREAD

**Issue by kentakayama** [laurencelundblade/t_cose#122]
How about changing the interface [`t_cose_sign_encode_start`](https://github.com/laurencelundblade/t_cose/blob/dev/src/t_cose_sign_sign.c#L100) and [`t_cose_sign_encode_finish`](https://github.com/laurencelundblade/t_cose/blob/dev/src/t_cose_sign_sign.c#L134) in dev branch?
This is close to #34 , but now we can ignore the backward compatibility on t_cose 2.0.
It will be much simpler, and easy to implement detached content Mac and Encrypt.

# Before
```
enum t_cose_err_t
t_cose_sign_encode_start(struct t_cose_sign_sign_ctx *me,
                         bool                         payload_is_detached,
                         QCBOREncodeContext          *cbor_encode_ctx)
{
    ...
    if(!payload_is_detached) {
        QCBOREncode_BstrWrap(cbor_encode_ctx);
    }
}

enum t_cose_err_t
t_cose_sign_encode_finish(struct t_cose_sign_sign_ctx *me,
                          struct q_useful_buf_c        aad,
                          struct q_useful_buf_c        detached_payload,
                          QCBOREncodeContext          *cbor_encode_ctx)
{
    if(q_useful_buf_c_is_null(detached_payload)) {
        /* Payload is inline, not detached */
        QCBOREncode_CloseBstrWrap2(cbor_encode_ctx, false, &signed_payload);
    } else {
        signed_payload = detached_payload;
    }
    ...
}

enum t_cose_err_t
t_cose_sign_one_short()
{
    return_value = t_cose_sign_encode_start(me, payload_is_detached, &encode_context);
    if(payload_is_detached) {
        QCBOREncode_AddNULL(&encode_context);
    } else {
        QCBOREncode_AddEncoded(&encode_context, payload);
    }
    if(!payload_is_detached) {
        payload = NULL_Q_USEFUL_BUF_C;
    }
    return_value = t_cose_sign_encode_finish(me, aad, payload, &encode_context);
}
```

# After
```
enum t_cose_err_t
t_cose_sign_one_short()
{
    /*
    COSE_Sign = [
        Headers,
        payload : bstr / nil,
        signatures : [+ COSE_Signature]
    ]
    */

    /* encode `[` and `Headers` */
    return_value = t_cose_sign_encode_start(me, &encode_context);

    /* encode payload */
    if(payload_is_detached) {
        QCBOREncode_AddNULL(&encode_context);
        //XXX: no need to execute       payload = NULL_Q_USEFUL_BUF_C;
    } else {
        QCBOREncode_BstrWrap(cbor_encode_ctx);
        QCBOREncode_AddEncoded(&encode_context, payload);
        QCBOREncode_CloseBstrWrap2(cbor_encode_ctx, false, &signed_payload);
    }

    /* encode (`signatures` or `signature`) and `]` */
    return_value = t_cose_sign_encode_finish(me, aad, payload, &encode_context);
}
```

**Comment by laurencelundblade** [comment]
Yes, the interface can change in t_cose 2.0, but we have to support the t_cose 1.0 interface in a backwards compatible mode.

Your change would make the internals of t_cose_sign simpler which is good, but it would also make the use of the two-step signing more complicated. Look at two_step_sign_example(). All the BstrWrap stuff that is in t_cose_sign_encode_start() and t_cose_sign_encode_finish() would have to be implemented by the caller making it harder to use the two-step option. Example code will help, but not completely simplify it. I also worry it will make the 1.0 compatibility more complicated.

How does this help with detached payload encrypt-then-sign? At some point there should be an encrypt-then-sign API in t_cose. It should work for detached and non-detached payloads. It would probably be the t_cose_message object/API/context.

**Comment by kentakayama** [comment]
With proposed interface the caller must call `QCBOREncode_BstrWrap()` and `QCBOREncode_CloseBstrWrap2()` on two-step signing. It is certainly harder because the caller may not know that the payload should be bstr-wrapped in COSE struct.
I'll modify the interface in my forked repository as a trial, so judge that the change is appropriate.

**Comment by laurencelundblade** [comment]
I have a pretty good idea what the calling code would look like.  I also can see how the t_cose 1.0 backwards compatibility mode can be handled too. 

I'm still trying to understand the benefit of this change.

I know for sure that it will simplify the internals of t_cose.

Are there use cases where it will benefit the user of t_cose? So far it just seems like it makes it harder for the user.  In particular, does it make things easier for encrypt-then-sign with detached content?

**Comment by laurencelundblade** [comment]
Fixed by https://github.com/laurencelundblade/t_cose/commit/baa6001217e75ea9460b3b6ae23858e873d111f7
