### ISSUE TITLE
Test Mac0 against other/external examples and test cases

### ISSUE THREAD

**Issue by laurencelundblade** [laurencelundblade/t_cose#126]
The Mac0 implementation only has tests against itself -- that it can validate what it computes. This is a convenient and necessary test, but there should be others against the output from other implementations of collections of know good examples (COSE_Sign1 is tested like this).

Some are available here: https://github.com/cose-wg/Examples/tree/master/mac0-tests

**Comment by davidvincze** [comment]
I put together a new Mac0 test case based on your recommendation and the cwt test in sign_verify.c, but it still has some issues.
It's WIP.

**Comment by davidvincze** [comment]
I've updated the PR:
- Fixing Mac0 implementation
- New test case to verify the implementation against a know good example (CWT was abandoned - alg. not supported currently)
