### ISSUE TITLE
t_cose_crypto_pub_key_sign() could be misleading

### ISSUE THREAD

**Issue by tamasban** [laurencelundblade/t_cose#23]
One can assume (misunderstand) that actually the public key is used to sign the data and not the private key.

Suggestions:
- t_cose_crypto_priv_key_sign().  It can be a good pair with t_cose_crypto_pub_key_verify()
- t_cose_crypto_sign().   An might t_cose_crypto_verify().

**Comment by ndevillard** [comment]
Agreed: this is a very confusing name. I would even go one step further and suggest t_cose_sign() and t_cose_verify(), and assume the reader knows crypto is used under the hood :-)

**Comment by laurencelundblade** [comment]
Fixed by #64
