### ISSUE TITLE
Nonce (IV) sizes for AES-{GCM, CCM, KW} differ from RFC 9053

### ISSUE THREAD

**Issue by kentakayama** [laurencelundblade/t_cose#282]
The `bits_iv_alg` returns different IV length specified in RFC 9053.

### AES-GCM
https://datatracker.ietf.org/doc/html/rfc9053#section-4.1
> The GCM mode is parameterized by the size of the authentication tag and the size of the nonce. This document fixes the size of the nonce at 96 bits.

### AES-CCM
https://datatracker.ietf.org/doc/html/rfc9053#section-4.2
| Name| 	Value| 	L| 	M| 	Key Length| 	Description|
|--|--|--|--|--|--|
| AES-CCM-16-128-128| 	30| 	16| 	128| 	128| 	AES-CCM mode 128-bit key, 128-bit tag, 13-byte nonce|
| AES-CCM-16-128-256| 	31| 	16| 	128| 	256| 	AES-CCM mode 256-bit key, 128-bit tag, 13-byte nonce|

### AES-KW
There is no initial vector, so it should return the default value `UINT32_MAX` .

**Comment by laurencelundblade** [comment]
Thank you, Ken!
