### ISSUE TITLE
No COSE detached content support

### ISSUE THREAD

**Issue by kentakayama** [laurencelundblade/t_cose#33]
Current t_cose seems not to support "detached content", defined in in RFC 8152 COSE section [4.1](https://tools.ietf.org/html/rfc8152#section-4.1).  
It sets `nil (0xF6)` at the payload instead of the bstr-wrapped target payload.  

The [latest SUIT manifest](https://tools.ietf.org/html/draft-ietf-suit-manifest-12#section-5.3) uses this functionality, and there are examples [here](https://tools.ietf.org/html/draft-ietf-suit-manifest-12#appendix-B.1).

**Comment by laurencelundblade** [comment]
Fixed by #34
