### ISSUE TITLE
no support for PS256

### ISSUE THREAD

**Issue by EvergreenHZ** [laurencelundblade/t_cose#43]
hi, can t_cose support PS256 signature verification algorithm(COSE_Sign1)? or can I get some hints to implement it.

**Comment by laurencelundblade** [comment]
Hi,

The design is with the intent to be able to accommodate this, but it is not there now. There is an adaptation layer for various crypto defined in t_cose_crypto.h.

The place to start is t_cose_crypto.h where the signature size constants need to be tweaked. All the keys and sigs go on the stack so adding support for an RSA algorithm will increase stack usage significantly. That will be OK unless you are on an embedded device.

Next work on t_cose_psa_crypto.c or on t_cose_openssl_crypto.c depending on which crypto lib you integrate with. You'll need to modify t_cose_crypto_pub_key_sign() and t_cose_crypto_pub_key_verify(). 

This won't be the easiest thing to do, but not the hardest either. The architecture of t_cose should support it.

(Sorry for the delay; had Covid)

**Comment by plietar** [comment]
I am planning on implementing this, assuming no one is already.

@laurencelundblade I see you've just opened PRs that are somewhat related to this, just want to check you aren't already working on it by any chance.

**Comment by laurencelundblade** [comment]
No one is working on it as far as I know. You work is welcome.

You can work against the master branch. The changes happening in the dev branch aren't in this area.

Thank you!
