### ISSUE TITLE
Build error when the test access the Mbed Crypto private variables

### ISSUE THREAD

**Issue by kentakayama** [laurencelundblade/t_cose#45]
Building t_cose fails with this error below when using latest Mbed TLS and Mbed Crypto without `MBEDTLS_ALLOW_PRIVATE_ACCESS` option.
```
$ make -f Makefile.psa
...
test/t_cose_make_psa_test_key.c: In function ‘check_for_key_pair_leaks’:
test/t_cose_make_psa_test_key.c:222:24: error: ‘mbedtls_psa_stats_t’ {aka ‘struct mbedtls_psa_stats_s’} has no member named ‘volatile_slots’; did you mean ‘private_volatile_slots’?
  222 |     return (int)(stats.volatile_slots +
      |                        ^~~~~~~~~~~~~~
      |                        private_volatile_slots
test/t_cose_make_psa_test_key.c:223:18: error: ‘mbedtls_psa_stats_t’ {aka ‘struct mbedtls_psa_stats_s’} has no member named ‘persistent_slots’; did you mean ‘private_persistent_slots’?
  223 |            stats.persistent_slots +
      |                  ^~~~~~~~~~~~~~~~
      |                  private_persistent_slots
test/t_cose_make_psa_test_key.c:224:18: error: ‘mbedtls_psa_stats_t’ {aka ‘struct mbedtls_psa_stats_s’} has no member named ‘external_slots’; did you mean ‘private_external_slots’?
  224 |            stats.external_slots +
      |                  ^~~~~~~~~~~~~~
      |                  private_external_slots
test/t_cose_make_psa_test_key.c:225:18: error: ‘mbedtls_psa_stats_t’ {aka ‘struct mbedtls_psa_stats_s’} has no member named ‘half_filled_slots’; did you mean ‘private_half_filled_slots’?
  225 |            stats.half_filled_slots +
      |                  ^~~~~~~~~~~~~~~~~
      |                  private_half_filled_slots
test/t_cose_make_psa_test_key.c:226:17: error: ‘mbedtls_psa_stats_t’ {aka ‘struct mbedtls_psa_stats_s’} has no member named ‘cache_slots’
  226 |            stats.cache_slots);
      |                 ^
make: *** [<builtin>: test/t_cose_make_psa_test_key.o] Error 1
```

These are introduced by [this commit in Mbed TLS](https://github.com/ARMmbed/mbedtls/commit/846f021de291c105c18031fa5d5c466917cb3cad#diff-8fe19c51d861f48010b3609673ee1dd94bb3eef20af920af31b36fc0dcb124c8L229) making several variables private.
[The macro](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/private_access.h#L27) `MBEDTLS_PRIVATE()` append prefix `private_` to each wrapped variable name if `MBEDTLS_ALLOW_PRIVATE_ACCESS` is not defined.

There are some options to fix this issue, I think.
- Do not allow t_cose users to use latest Mbed TLS/Crypto without the `MBEDTLS_ALLOW_PRIVATE_ACCESS` option
- Add CRYPTO_CONFIG_OPTS like `T_COSE_DISABLE_PSA_KEY_PAIR_LEAK_TEST` in Makefile.psa to skip the test

```
diff --git a/test/t_cose_make_psa_test_key.c b/test/t_cose_make_psa_test_key.c
index 245d4b7..cfa9e81 100644
--- a/test/t_cose_make_psa_test_key.c
+++ b/test/t_cose_make_psa_test_key.c
@@ -210,8 +210,9 @@ void free_ecdsa_key_pair(struct t_cose_key key_pair)
  */
 int check_for_key_pair_leaks()
 {
-#if defined(T_COSE_USE_PSA_CRYPTO_FROM_MBED_CRYPTO11)
-    /* No way to check for leaks with MBED Crypto 1.1 */
+#if defined(T_COSE_USE_PSA_CRYPTO_FROM_MBED_CRYPTO11) || \
+    defined(T_COSE_DISABLE_PSA_KEY_PAIR_LEAK_TEST)
+    /* No way to check for leaks with Mbed Crypto 1.1 and above 3.1 */
     return 0;
 
 #else
```

**Comment by laurencelundblade** [comment]
Hi Ken,

This is only for a test case so it's not too big of a problem. Anyone can *use* t_cose in their app without any change. They just can't run the test suite.

The question to answer first is whether there is any way to check for key pair leaks using public Mbed function. If there are then we should use them.  I haven't looked yet.

If not I'd probably define MBEDTLS_ALLOW_PRIVATE_ACCESS just for the test code so the tests can continue to run.

**Comment by kentakayama** [comment]
I see your point, this is not a big problem.

A work around came up to my mind: 
`make -f Makefile.psa libt_cose.a`
not to build the test code.
