### ISSUE TITLE
Support custom headers

### ISSUE THREAD

**Issue by laurencelundblade** [laurencelundblade/t_cose#5]
Be able to add arbitrary headers when encoding and be able to call out to custom decoder when encountering an unknown header.

**Comment by letmaik** [comment]
I'm interested in custom headers specifically for decoding. How much would it take to support this?

**Comment by letmaik** [comment]
@laurencelundblade How much of this is implemented in the develop branch already? Is it just the string label support that's missing?
cc @plietar

**Comment by laurencelundblade** [comment]
Fixed by #78 and other PRs
