### ISSUE TITLE
simple memory leak

### ISSUE THREAD

**Issue by kik** [laurencelundblade/t_cose#76]
hi,

missing call to `EVP_MD_CTX_free()` here.

https://github.com/laurencelundblade/t_cose/blob/d5ff4e282d8af34e5756627cf877ab399e7e51af/crypto_adapters/t_cose_openssl_crypto.c#L624

**Comment by laurencelundblade** [comment]
Address by #94

**Comment by laurencelundblade** [comment]
Fixed by #94
