### ISSUE TITLE
Error codes in t_cose_sign_sign.c

### ISSUE THREAD

**Issue by hannestschofenig** [laurencelundblade/t_cose#96]
t_cose_sign_encode_start() in t_cose_sign_sign.c lists error codes in 

https://github.com/laurencelundblade/t_cose/blob/240b048f2a5d3254d04afa2f288bd733d0a18687/src/t_cose_sign_sign.c#L45
https://github.com/laurencelundblade/t_cose/blob/240b048f2a5d3254d04afa2f288bd733d0a18687/src/t_cose_sign_sign.c#L60

It would be better to define the error codes in t_cose_common.h.

**Comment by laurencelundblade** [comment]
Fixes (not sure which PR).
